baseURL = "https://chetankm-cs.github.io/"
languageCode = "en-us"
title = "Chetan K M"

[params]
  description = "Thoughts on software engineering, technology, and building things."
  author = "Chetan K M"
  email = "pop.chetan@gmail.com"
  twitterUsername = "chetan_km"
  githubUsername = "chetankm-cs"

[outputs]
  home = ["HTML", "RSS"]
